app_id: "b278d706-fc04-46f2-ae05-cf24b5b18225"
app_secret: "yUkT_N~JG4JScp52~_cxa1cq.TDt4.1Iwg"
redirect: "http://localhost:8000/callback"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"

